name: Deploy Zola Site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Zola
        run: |
          curl -s https://www.getzola.org/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Build site
        run: zola build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public

